{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ include "valkey.namespace" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "valkey.secretPasswordKey" . }}: {{ include "valkey.password" . | b64enc | quote }}
{{- end }}
{{- end }}