{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "valkey.password" . | b64enc | quote }}
{{- end }}