apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ include "valkey.namespace" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  {{- end }}
  ports:
  - name: valkey
    port: {{ .Values.service.port }}
    targetPort: valkey
  {{- if .Values.sentinel.enabled }}
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    targetPort: sentinel
  {{- end }}
  {{- with .Values.service.extraPorts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-headless
  namespace: {{ include "valkey.namespace" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: valkey
    port: {{ .Values.service.port }}
    targetPort: valkey
  {{- if .Values.sentinel.enabled }}
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    targetPort: sentinel
  {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}